## Start the projects


In [2]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [3]:
import pandas as pd
data_set = pd.read_csv("spam.csv", encoding='latin-1')

In [4]:
data_set.shape

(5572, 5)

In [5]:
data_set.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN


In [6]:
data_set[['v1']].value_counts()

v1  
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [8]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [9]:
corpus = []
for i in range(0,len(data_set)):
    messages = re.sub('[^a-zA-Z]',' ' ,data_set['v2'][i])
    messages = messages.lower()
    messages = messages.split()

    messages =[lemmatizer.lemmatize(word) for word in messages]
    messages = ' '.join(messages)
    corpus.append(messages)
    
    

In [11]:
print(corpus)

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat', 'ok lar joking wif u oni', 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s', 'u dun say so early hor u c already then say', 'nah i don t think he go to usf he life around here though', 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv', 'even my brother is not like to speak with me they treat me like aid patent', 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune', 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only', 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile update co f

In [10]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, data_set['v2']) if i<1] ## 

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

## above two block contain a good logics ^^^^^

In [12]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

## The gensim.utils.simple_preprocess() function is a basic, convenient utility for converting a raw text document (string) into a list of cleaned, individual tokens (words). It performs several common preprocessing steps automatically

In [18]:
word = []
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
        word.append(simple_preprocess(sent))

In [19]:
word

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [20]:
word[1]

['ok', 'lar', 'joking', 'wif', 'oni']

In [21]:
import gensim

In [22]:
## lets train word2vec from scrach
model=gensim.models.Word2Vec(word,epochs=10)

In [23]:
## To Get All the Vocabulary
model.wv.index_to_key

['you',
 'to',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'be',
 'if',
 'ur',
 'will',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'how',
 'go',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'out',
 'all',
 'know',
 'll',
 'come',
 'like',
 'time',
 'good',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'text',
 'only',
 'love',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'home',
 'don',
 'stop',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'mobile',
 'still',
 'take',
 'back',
 'da',
 'reply',
 'our',
 'think',
 'tell',
 'dont',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'they',
 'any',
 'pls',
 'her',
 'please',
 'ha',
 'co',
 'msg',
 'did',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'make',
 'here',
 'night',
 'who',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'clai

In [24]:
model.corpus_count #  vocabulary count

5569

In [25]:
model.epochs

10

In [26]:
model.wv.similar_by_word('good')

[('morning', 0.9759886264801025),
 ('happy', 0.9644551873207092),
 ('my', 0.9504446983337402),
 ('hope', 0.9470418691635132),
 ('great', 0.9372833967208862),
 ('day', 0.9359973073005676),
 ('did', 0.9297662377357483),
 ('dear', 0.9285566210746765),
 ('well', 0.928256630897522),
 ('love', 0.9271910786628723)]

In [27]:
model.wv['good'].shape

(100,)

In [28]:
print(model.wv['good'])

[-0.5988221   0.16847534  0.28253567 -0.24680008  0.3077348  -0.30820712
  0.6117887   0.669828   -0.3361873  -0.36645475  0.13814361 -0.73393244
 -0.18018396  0.14121583 -0.04236698 -0.33254343  0.22035077 -0.34736103
 -0.03448528 -0.79261565  0.2775476   0.10797592  0.21806784 -0.44699827
  0.05363379 -0.08040969 -0.08445853 -0.496607   -0.49200195 -0.4508853
  0.39552101 -0.06457053  0.3509392  -0.12842597 -0.36902723 -0.07733145
  0.05452991 -0.5295207  -0.08477703 -0.42536238  0.18453212  0.09163287
 -0.06690785  0.20007376  0.4547958  -0.39343482 -0.17000295 -0.2424937
 -0.0499904   0.5650262   0.55880266  0.35571623 -0.12542123 -0.09255368
  0.05248657  0.04171283 -0.01651666  0.3974567  -0.39838898  0.0378395
  0.0464122   0.13681188 -0.01698533 -0.14286883 -0.53892434  0.08583169
 -0.02052281  0.28230864 -0.58529884  0.25658932 -0.05988366  0.7231385
  0.16050619  0.07070924  0.92270654 -0.18793544  0.5455654  -0.417628
 -0.58801913  0.1982543  -0.19855452  0.4741158  -0.06978

In [29]:
## average word2vec this convert whole 100 dim average 
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [30]:
!pip install tqdm

In [31]:
from tqdm import tqdm

In [32]:
#apply for the entire sentences
import numpy as np
x=[]
for i in tqdm(range(len(word))):
    x.append(avg_word2vec(word[i]))

  0%|                                                                                         | 0/5569 [00:00<?, ?it/s]C:\Users\Lenovo\anaconda3\envs\dl-tf215\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\Lenovo\anaconda3\envs\dl-tf215\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|████████████████████████████████████████████████████████████████████████████| 5569/5569 [00:00<00:00, 6491.54it/s]


In [37]:
len(x)
x[1].shape

(100,)

In [36]:
x[1]

array([-0.31940502,  0.24457344,  0.13574228,  0.07682874,  0.10944077,
       -0.28880337,  0.13780951,  0.57692695, -0.31392968, -0.09670364,
       -0.17873235, -0.28229427, -0.18780573,  0.19615746,  0.13638452,
       -0.41175303,  0.10561364, -0.2713031 , -0.00794989, -0.4685077 ,
        0.16489238,  0.14356261,  0.12696412, -0.13316365, -0.05652644,
       -0.05517327, -0.27687982, -0.4116544 , -0.32746622,  0.13775375,
        0.2569478 , -0.05685064, -0.04458925, -0.35241145, -0.0508706 ,
        0.24214551, -0.04228802, -0.1652357 , -0.10349128, -0.48928547,
        0.08269592, -0.07356399, -0.10910806, -0.07242475,  0.20936497,
       -0.14003253,  0.04239792, -0.15065913,  0.2333928 ,  0.3167724 ,
        0.04965591, -0.13665353, -0.06917042,  0.01385801, -0.08196232,
        0.02707123,  0.20092444,  0.08943228, -0.38442904,  0.05273212,
        0.02323897,  0.05984046, -0.12855205, -0.12265208, -0.3155197 ,
        0.10806718,  0.1054638 ,  0.12327659, -0.34962976,  0.28

In [38]:
## Dependent Features
## Output Features
y = data_set[list(map(lambda x: len(x)>0 ,corpus))]
y = pd.get_dummies(y['v1'])
y = y.iloc[:,0].values

In [39]:
x[0].reshape(1,-1).shape  ## just like this convert the sentences in the vertical after takeing the average 

(1, 100)

In [48]:
## this is the final independent features
df = pd.DataFrame()
rows = []
for i in range(len(x)):
    rows.append(pd.DataFrame(x[i].reshape(1,-1)))

df = pd.concat(rows, ignore_index=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_344\169867247.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(rows, ignore_index=True)


In [41]:
df.head() ## this is our 2 sentences 

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.260842,0.238539,0.130780,0.060437,0.116970,-0.296234,0.187931,0.532164,-0.307433,-0.100904,...,0.209439,0.190914,0.116983,0.115138,0.384889,0.316165,0.075260,-0.185325,0.089313,-0.141469
1,-0.319405,0.244573,0.135742,0.076829,0.109441,-0.288803,0.137810,0.576927,-0.313930,-0.096704,...,0.246249,0.121495,0.035032,0.115654,0.364542,0.343905,0.041348,-0.221160,-0.011947,-0.205940
2,-0.127732,0.307255,0.149160,0.242077,0.156854,-0.628251,0.087863,0.475466,-0.340151,-0.031169,...,0.372784,0.152896,0.065895,0.123843,0.364278,0.114833,-0.042982,-0.354134,0.096894,0.071057
3,-0.495970,0.279044,0.178277,0.042280,0.178481,-0.303459,0.182369,0.781345,-0.457366,-0.206590,...,0.280616,0.092597,0.022100,0.185746,0.448087,0.496320,0.062927,-0.318248,-0.019211,-0.256439
4,-0.389620,0.205790,0.155668,-0.038522,0.207927,-0.291625,0.196426,0.687064,-0.402403,-0.272931,...,0.259032,0.101654,0.092834,0.205655,0.404218,0.455593,0.050741,-0.267210,0.024158,-0.168436


In [31]:
y

array([ True,  True, False, ...,  True,  True,  True])

In [32]:
y = pd.DataFrame(y,columns=["Output"])
y.head()

,Output
0,True
1,True
2,False
3,True
4,True


In [39]:
y = y['Output'].map({True:1, False:0}).values

In [40]:
y

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [41]:
df['Output']=y

In [42]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Output
0,-0.183170,0.222997,0.153361,0.109644,0.086679,-0.293325,0.230363,0.543249,-0.310337,-0.106606,...,0.207710,0.123149,0.126751,0.432232,0.251819,0.077510,-0.186242,0.142142,-0.069534,1
1,-0.232455,0.245009,0.132182,0.138226,0.083082,-0.260376,0.208170,0.619490,-0.347623,-0.093059,...,0.155470,0.054438,0.122797,0.436928,0.242767,0.042494,-0.250685,0.057134,-0.127527,1
2,-0.093369,0.209603,0.219317,0.277417,0.106411,-0.577805,0.079698,0.362117,-0.361625,-0.019178,...,0.223600,0.057958,0.114549,0.356591,0.120369,-0.030153,-0.363944,0.144683,0.129973,0
3,-0.381793,0.332395,0.147445,0.107370,0.158902,-0.318498,0.317837,0.872176,-0.502717,-0.240331,...,0.137957,0.042948,0.222883,0.586180,0.352135,0.075686,-0.329418,0.096323,-0.158054,1
4,-0.298835,0.262789,0.152603,0.044043,0.196801,-0.344279,0.293050,0.746309,-0.408768,-0.312897,...,0.138681,0.103582,0.238001,0.513579,0.363109,0.040641,-0.270515,0.108734,-0.100848,1


In [46]:
df.shape

(5569, 101)

In [45]:
df.isnull().sum()

0         12
1         12
2         12
3         12
4         12
          ..
96        12
97        12
98        12
99        12
Output     0
Length: 101, dtype: int64

In [47]:
df.dropna(axis=0,inplace=True)

In [48]:
df.shape

(5557, 101)

In [49]:
x = df.drop(["Output"],axis=1)

In [50]:
x

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.183170,0.222997,0.153361,0.109644,0.086679,-0.293325,0.230363,0.543249,-0.310337,-0.106606,...,0.238091,0.207710,0.123149,0.126751,0.432232,0.251819,0.077510,-0.186242,0.142142,-0.069534
1,-0.232455,0.245009,0.132182,0.138226,0.083082,-0.260376,0.208170,0.619490,-0.347623,-0.093059,...,0.279346,0.155470,0.054438,0.122797,0.436928,0.242767,0.042494,-0.250685,0.057134,-0.127527
2,-0.093369,0.209603,0.219317,0.277417,0.106411,-0.577805,0.079698,0.362117,-0.361625,-0.019178,...,0.406168,0.223600,0.057958,0.114549,0.356591,0.120369,-0.030153,-0.363944,0.144683,0.129973
3,-0.381793,0.332395,0.147445,0.107370,0.158902,-0.318498,0.317837,0.872176,-0.502717,-0.240331,...,0.276166,0.137957,0.042948,0.222883,0.586180,0.352135,0.075686,-0.329418,0.096323,-0.158054
4,-0.298835,0.262789,0.152603,0.044043,0.196801,-0.344279,0.293050,0.746309,-0.408768,-0.312897,...,0.251329,0.138681,0.103582,0.238001,0.513579,0.363109,0.040641,-0.270515,0.108734,-0.100848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5564,-0.070755,0.271010,0.302241,0.226362,0.086548,-0.411631,0.243294,0.455738,-0.327275,-0.061209,...,0.322723,0.335144,0.251875,0.076001,0.431104,0.199309,0.033627,-0.288069,0.280899,0.100607
5565,-0.260562,0.233096,0.148392,0.126524,0.169279,-0.371357,0.264630,0.662305,-0.417172,-0.170825,...,0.352368,0.160874,0.060598,0.166937,0.487676,0.267446,-0.043474,-0.276946,0.044736,-0.041754
5566,-0.247688,0.240987,0.165557,0.004637,0.129761,-0.357115,0.290528,0.648426,-0.316069,-0.235900,...,0.195566,0.249397,0.202900,0.197564,0.524485,0.383367,0.155453,-0.130570,0.226356,-0.109521
5567,-0.196854,0.225566,0.161549,0.076375,0.141806,-0.386066,0.230745,0.587332,-0.340450,-0.193532,...,0.254941,0.222095,0.170023,0.201129,0.475403,0.334955,0.095082,-0.175879,0.153938,-0.075389


In [51]:
y = df["Output"]

In [52]:
y

0       1
1       1
2       0
3       1
4       1
       ..
5564    0
5565    1
5566    1
5567    1
5568    1
Name: Output, Length: 5557, dtype: int64

In [53]:
## Train Test Split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [55]:
x_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
526,-0.059028,0.197150,0.260196,0.289986,0.082956,-0.523905,0.081126,0.321466,-0.319157,0.062550,...,0.392588,0.274617,0.118261,0.071240,0.347951,0.127909,-0.006070,-0.352294,0.191757,0.116351
5296,-0.292865,0.201527,0.182857,-0.039622,0.176401,-0.364899,0.328343,0.547624,-0.278149,-0.204496,...,0.126203,0.164598,0.148081,0.213904,0.485909,0.338205,0.148293,-0.178434,0.280751,-0.085439
3416,0.002000,0.245601,0.242856,0.273978,0.087336,-0.617146,0.163380,0.477830,-0.264272,-0.075363,...,0.502119,0.276010,0.107048,0.056574,0.451117,0.209229,-0.072879,-0.369092,0.123549,0.122265
158,-0.148481,0.242988,0.272410,0.172489,0.177005,-0.591751,0.253074,0.523176,-0.270160,-0.172257,...,0.438825,0.218568,0.110193,0.087573,0.460760,0.234782,-0.078427,-0.430594,0.208803,0.162494
1610,-0.133282,0.292455,0.115262,0.066758,0.087511,-0.275128,0.339507,0.787256,-0.247411,-0.248664,...,0.362504,0.236053,0.145654,0.150297,0.564071,0.404793,-0.025644,-0.122065,-0.023254,-0.127611


In [56]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [58]:
classifier.fit(x_train,y_train)

RandomForestClassifier()

In [63]:
y_pred=classifier.predict(x_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [61]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.9838129496402878


In [62]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.92      0.94       148
           1       0.99      0.99      0.99       964

    accuracy                           0.98      1112
   macro avg       0.97      0.96      0.96      1112
weighted avg       0.98      0.98      0.98      1112



In [66]:
user_input =input("type a massage heare").lower()
## for this i have to pass it from whole process
# ?result = classifier.predict(user_input)

type a massage heare hii
